version: "3"

services:
  db:
    container_name: busuu-db
    image: postgres:13
    environment:
      POSTGRES_DB: exercises_db
      POSTGRES_USER: busuu
      POSTGRES_PASSWORD: busuu
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./busuu.sql:/docker-entrypoint-initdb.d/busuu.sql
      - ./files:/files
    ports:
      - 5432:5432
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local
